theme: jekyll-theme-cayman
title: Kanban University - Good Deeds Program
description: Home of the Kanban University Good Deeds program

baseurl: "/gooddeeds" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://kanbanuniversity.github.io" # change this to the base hostname & protocol for your site

header_page_refs: ['about', 'manage', 'program', 'contact']